version: "3.7"
services:
  
  mysqldb:
    image: mysql/mysql-server:latest
    restart: always
    
    environment:
      MYSQL_HOST: localhost
      
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      
        
    
    ports:
      - "3306:3306"
    expose:
      - 3306  
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  # node-api:
  #   build: .
  #   command: npm start

  #   ports: 
  #     - "1234:1234"  
volumes: 
  db-config:
  db-data:  


  
